@startuml
actor "Aluno" as Aluno
participant "Sistema" as Sistema

activate Aluno
Aluno -> Sistema : Solicitar saldo e extrato
activate Sistema

Sistema -> Sistema : Buscar informações do aluno
Sistema -> Aluno : Retornar saldo e extrato

deactivate Sistema
deactivate Aluno
@enduml