@startuml
actor "Relógio" as Relogio
participant "Sistema" as Sistema
participant "Empresa Parceira" as Empresa

activate Relogio
Relogio -> Sistema : Iniciar envio de notificação para empresa
activate Sistema

Sistema -> Empresa : Enviar notificação
activate Empresa
Empresa --> Sistema : Confirmar recebimento
deactivate Empresa

deactivate Sistema
deactivate Relogio
@enduml