@startuml
actor "Professor" as Professor
participant "Sistema" as Sistema
participant "Aluno" as Aluno

activate Professor
Professor -> Sistema : Solicitar envio de notificação para aluno
activate Sistema

Sistema -> Aluno : Enviar notificação
activate Aluno
Aluno --> Sistema : Confirmar recebimento
deactivate Aluno

Sistema -> Professor : Confirmar envio da notificação
deactivate Sistema
deactivate Professor
@enduml