@startuml

left to right direction

actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Empresa Parceira" as Empresa
actor "Relógio" as Relogio

usecase "Cadastrar" as UC1
usecase "Enviar Moedas" as UC3
usecase "Consultar Saldo e Extrato (Aluno)" as UC4
usecase "Consultar Saldo e Extrato (Professor)" as UC5
usecase "Cadastrar Vantagem" as UC7
usecase "Trocar Moedas por Vantagem" as UC8
usecase "Enviar Cupom para Aluno" as UC9
usecase "Notificar Aluno" as UC11
usecase "Notificar Empresa Parceira" as UC10

Aluno -- UC1
Aluno -- UC4
Aluno -- UC8
Aluno -- UC9

Professor -- UC3
Professor -- UC5
Professor -- UC11

Relogio -- UC3

Empresa -- UC7
Empresa -- UC10

UC3 .> UC11 : includes

@enduml